version: build-{build}.{branch}

build: off

clone_folder: c:\gopath\src\github.com\lifezq\goutils

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  
before_test:
  - set PATH=C:\go\bin;%PATH%
  - set GOROOT=C:\go
  - go vet ./...

test_script:
  - go test ./...
  
